**Modèle de machine learning pour prédire les absences RH**

Ce modèle supervisé de machine learning permet d'anticiper les absences d'une personne au sein d'une équipe, selon ses caractéristiques notamment, age, sexe et équipe ainsi que volume d'absences passées

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
# Charger les données
df = pd.read_csv("employes_1000.v2.csv")

In [ ]:
df.head(5)

   Matricule       Nom     Prénom  Age  ancienneté  BU  Jours-dabsence
0          1     DUMAS      JULIE   38          22   1             161
1          2   LAURENT    PATRICK   83          38   1              14
2          3      DIAZ      ANDRE   27          22   2              15
3          4  ROUSSEAU  CHARLOTTE   40          23   3              58
4          5    GARCIA      MANON   46          24   2              60

In [38]:
# #harmonization of the dates
# df["date-de-naissance"] = pd.to_datetime(df["date-de-naissance"],
#     dayfirst=True,
#     errors="coerce"
# )

In [39]:
# df[df["date-de-naissance"].isna()]

In [40]:
df.head(5)

   Matricule       Nom     Prénom  Age  ancienneté  BU  Jours-dabsence
0          1     DUMAS      JULIE   38          22   1             161
1          2   LAURENT    PATRICK   83          38   1              14
2          3      DIAZ      ANDRE   27          22   2              15
3          4  ROUSSEAU  CHARLOTTE   40          23   3              58
4          5    GARCIA      MANON   46          24   2              60

In [17]:
X=df.drop(columns=["Matricule", "Nom", "Prénom", "Jours-dabsence"])
y=df["Jours-dabsence"]

In [18]:
df["BU"] = pd.to_numeric(df["BU"], errors="coerce")
df.groupby("Age")["BU"].mean()

Age
25    2.200000
26    2.333333
27    1.934783
28    2.032258
29    2.171429
        ...
82    1.666667
83    1.750000
84    2.333333
85    2.200000
86    1.666667
Name: BU, Length: 61, dtype: float64

In [19]:
# Créer le pipeline
model = Pipeline([
    ("preprocessing", Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler())
    ])),
    ("classifier", LogisticRegression(max_iter=1000))
])

In [20]:
X_train, X_test, y_train, y_test=train_test_split(X, y, test_size=0.2, random_state=42)

In [21]:
# Entraîner le modèle
model.fit(X_train, y_train)

# Prédire sur les données de test
y_pred = model.predict(X_test)

# Évaluer le modèle
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy :", accuracy)

Accuracy : 0.01

In [22]:
df.head(5)

   Matricule       Nom     Prénom  Age  ancienneté  BU  Jours-dabsence
0          1     DUMAS      JULIE   38          22   1             161
1          2   LAURENT    PATRICK   83          38   1              14
2          3      DIAZ      ANDRE   27          22   2              15
3          4  ROUSSEAU  CHARLOTTE   40          23   3              58
4          5    GARCIA      MANON   46          24   2              60

In [32]:
nouvelle_personne = {
    "Age": 83,
    "ancienneté": 10,	
    "BU":3	  
}

# Le DataFrame doit avoir le même nom de colonne que X
nouvelle_donnee = pd.DataFrame([nouvelle_personne])

In [33]:
probabilite_absence = model.predict_proba(nouvelle_donnee)[0][1]
probabilite_absence

np.float64(0.0030752214088740786)